using System;
using UnityEngine;

namespace DRAUM.CMS
{
    /// <summary>
    /// Модель тега контента
    /// </summary>
    [System.Serializable]
    public class ContentTag
    {
        [Header("Tag Info")]
        public string Name;
        public string Description;
        public Color Color = Color.white;
        
        [Header("Settings")]
        public bool IsAutoGenerated;
        public bool IsHidden;
        public int UsageCount;
        
        public ContentTag()
        {
            Name = "New Tag";
            Description = "";
            Color = Color.white;
            IsAutoGenerated = false;
            IsHidden = false;
            UsageCount = 0;
        }
        
        public ContentTag(string name, string description = "", Color? color = null, bool isAutoGenerated = false)
        {
            Name = name;
            Description = description;
            Color = color ?? Color.white;
            IsAutoGenerated = isAutoGenerated;
            IsHidden = false;
            UsageCount = 0;
        }
    }
}
